function [fitresult, gof] = fitExpoential(trace)
%CREATEFIT(XX2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: xx2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Jan-2023 15:19:07


%% Fit: 'untitled fit 1'.
fit_a = []; fit_b = [];
for kk = 1:size(trace, 3)
    [xData, yData] = prepareCurveData( [], trace(:,:,kk) );
    
    % Set up fittype and options.
    ft = fittype( 'exp1' );
    opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
    opts.Display = 'Off';
    opts.Lower = [0 -Inf];
    opts.StartPoint = [trace(1) -1e-06];
    opts.Upper = [Inf 1e-04];
    
    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );
    fit_b(end+1) = fitresult.b;
end
warning('off','curvefit:cfit:subsasgn:coeffsClearingConfBounds')
fitresult.b = mean(fit_b);
fitresult.a = 1;
warning('on','curvefit:cfit:subsasgn:coeffsClearingConfBounds')



